name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: yarn
    - run: yarn --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build
        single-commit: true